export const MODAL_NOTICONTACT_SHOW = 'MODAL_NOTICONTACT_SHOW'
export const MODAL_NOTICONTACT_ClOSE = 'MODAL_NOTICONTACT_ClOSE'

export const MODAL_MESS_CON_SHOW = 'MODAL_MESS_CON_SHOW'
export const MODAL_MESS_CON_CLOSE = 'MODAL_MESS_CON_CLOSE'