
export const ITEM_FETCH = 'ITEM_FETCH'
export const FETCH_SUCESS = 'FETCH_SUCESS'

export const FETCH_API_REQUEST = 'FETCH_API_REQUEST'
export const CHANGEPAGE = 'CHANGEPAGE'

export const FETCH_RECENTCHATS_REQUEST = 'FETCH_RECENTCHATS_REQUEST'
export const FETCH_RECENTCHATS_SUCESS = 'FETCH_RECENTCHATS_SUCESS'

export const FETCH_GROUPS_REQUEST = 'FETCH_GROUPS_REQUEST'
export const FETCH_GROUPS_SUCCESS = 'FETCH_GROUPS_SUCCESS'

export const FETCH_GETUSERS_REQUEST = 'FETCH_GETUSERS_REQUEST'
export const FETCH_GETUSERS_SUCCESS = 'FETCH_GETUSERS_SUCCESS'

export const FETCH_USER_USERS_RECENTCHAT_REQUEST = 'FETCH_USER_USERS_RECENTCHAT_REQUEST'
export const FETCH_USER_USERS_RECENTCHAT_SUCCESS = 'FETCH_USER_USERS_RECENTCHAT_SUCCESS'

export const FETCH_CREATE_CHAT_REQUEST = 'FETCH_CREATE_CHAT_REQUEST'
export const FETCH_CREATE_CHAT_SUCCESS = 'FETCH_CREATE_CHAT_SUCCESS'

export const FETCH_CREATE_GROUP_CHAT_REQUEST = 'FETCH_CREATE_GROUP_CHAT_REQUEST'
export const FETCH_CREATE_GROUP_CHAT_SUCCESS = 'FETCH_CREATE_GROUP_CHAT_SUCCESS'

export const USER_ONLINE = 'USER_ONLINE'
export const USER_MESSAGE = 'USER_MESSAGE'
export const RECIVE_MESSAGE = 'RECIVE_MESSAGE'
export const USER_LOGON = 'USER_LOGON'

export const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST'
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS'
export const FETCH_LOGIN_NOTSUCCESS = 'FETCH_LOGIN_NOTSUCCESS'

export const FETCH_DOWNFILE = 'FETCH_DOWNFILE'

export const FETCH_AVATAR_USER_REQUEST = 'FETCH_AVATAR_USER_REQUEST'
export const FETCH_AVATAR_USER_SUCCESS = 'FETCH_AVATAR_USER_SUCCESS'
export const FETCH_AVATAR_USER_NOTSUCCESS = 'FETCH_AVATAR_USER_NOTSUCCESS'

export const FETCH_CONTACTS_REQUEST = 'FETCH_CONTACTS_REQUEST'
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS'
export const FETCH_CONTACTS_NOSUCCESS = 'FETCH_CONTACTS_NOSUCCESS'

export const FETCH_CREATE_CONTACT_REQUEST = 'FETCH_CREATE_CONTACT_REQUEST'
export const FETCH_CREATE_CONTACT_SUCCESS = 'FETCH_CREATE_CONTACT_SUCCESS'
export const FETCH_CREATE_CONTACT_NOTSUCCESS = 'FETCH_CREATE_CONTACT_NOTSUCCESS'

export const FETCH_MESSSAGE_CONTACT_REQUEST = 'FETCH_MESSSAGE_CONTACT_REQUEST'
export const FETCH_MESSSAGE_CONTACT_SUCCESS = 'FETCH_MESSSAGE_CONTACT_SUCCESS'
export const FETCH_MESSSAGE_CONTACT_NOTSUCCESS = 'FETCH_MESSSAGE_CONTACT_NOTSUCCESS'

export const LOG_MESSAGE = 'LOG_MESSAGE'
export const LOG_MESSAGE_SUCCESS = 'LOG_MESSAGE_SUCCESS'

